CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic -g3

default : test3

test3:
	g++ $(CXXFLAGS) test3.cpp BigNum.cpp -o main

test2:
	g++ $(CXXFLAGS) test2.cpp BigNum.cpp -o main

test1:
	g++ $(CXXFLAGS) test1.cpp BigNum.cpp -o main

test:
	g++ $(CXXFLAGS) test.cpp BigNum.cpp -o main
